# --------------------
# Define arguments.
# --------------------

# ==================== Alas ====================

Scheduler:
  Enable:
    type: checkbox
    value: false
    option: [ true, false ]
  NextRun: 2020-01-01 00:00:00
  Command: Alas
  ServerUpdate:
    value: 06:00
    display: hide
Emulator:
  Serial:
    value: auto
    valuetype: str
  GameClient:
    value: android
    option: [ android, cloud_android ]
    display: hide
  PackageName:
    value: auto
    option: [ auto, ]
  GameLanguage:
    value: cn
    option: [ auto, cn, en ]
    display: hide
  ScreenshotMethod:
    value: auto
    option: [
      auto,
      ADB,
      ADB_nc,
      uiautomator2,
      aScreenCap,
      aScreenCap_nc,
      DroidCast,
      DroidCast_raw,
      scrcpy,
      nemu_ipc,
    ]
  ControlMethod:
    value: MaaTouch
    option: [ minitouch, MaaTouch ]
  AdbRestart: false
EmulatorInfo:
  Emulator:
    value: auto
    option: [
      auto,
      NoxPlayer,
      NoxPlayer64,
      BlueStacks4,
      BlueStacks5,
      BlueStacks4HyperV,
      BlueStacks5HyperV,
      LDPlayer3,
      LDPlayer4,
      LDPlayer9,
      MuMuPlayer,
      MuMuPlayerX,
      MuMuPlayer12,
      MEmuPlayer,
    ]
  name:
    value: null
    type: textarea
  path:
    value: null
    type: textarea
Error:
  Restart:
    value: game
    option: [ game, game_emulator ]
  SaveError: true
  ScreenshotLength: 1
  OnePushConfig:
    type: textarea
    mode: yaml
    value: 'provider: null'
Optimization:
  ScreenshotInterval: 0.3
  CombatScreenshotInterval: 1.0
  WhenTaskQueueEmpty:
    value: stay_there
    option: [ stay_there, goto_main, close_game ]

# ==================== Daily ====================

DailyQuestOptions:
  TransKaoGongTicket:
    type: checkbox
    value: 1
  VisitOthersForClivia:
    type: checkbox
    value: 0
  DailyJinGeWinReward:
    type: checkbox
    value: 0
  AutoDailyPassword:
    type: checkbox
    value: 0

DailyStorage:
  DailyLiveness:
    stored: StoredDailyLiveness
    order: 1
    color: "#ffcf70"
    display: display
  JinGeDailyWinReward:
    stored: StoredJinGeDailyWinReward
    display: display
  AutoDailyPassword:
    stored: StoredAutoDailyPassword
    display: display
  CelebrityInteract:
    stored: StoredCelebrityInteract
    display: display
  GuildSignIn:
    stored: StoredGuildSignIn
    display: display
  OfficeAffair:
    stored: StoredOfficeAffair
    display: display
  OfficeBuildFurniture:
    stored: StoredOfficeBuildFurniture
    display: display
  CatteryPlayWithCat:
    stored: StoredCatteryPlayWithCat
    display: display
  CatteryFeedCat:
    stored: StoredCatteryFeedCat
    display: display
  GetFriendshipPoint:
    stored: StoredGetFriendshipPoint
    display: display







Dungeon:
  Team:
    value: 1
    option: [1,2,3,4,5]
#  DailyJinGe:
#    type: checkbox
#    value: 0
  UseSoonExpiredMeat:
    type: checkbox
    value: 0
    display: hide
  DailyBaoXuPlan:
    stored: StoredDailyBaoXu
    display: display
  DailyJingYuanPlan:
    stored: StoredDailyJingYuan
    display: display
  DailyGuShiFengYunPlan:
    stored: StoredDailyBaoXu
    display: hide





MealPower:
  UseTongBaoBuyExpiredPower:
    type: checkbox
    value: 0

GuildActivity:
  OpenActivityList:
    value: 0
    display: hide
  ClearShaPanFlag:
    type: checkbox
    value: 0


GuildMission:
  DailyGuildMission:
    stored: StoredDailyGuildMission
    display: display
  WeeklyLiveness:
    value: 0
    display: hide

Cosplay:
  SendCosplayStatus:
    type: checkbox
    value: 0
  SendStatusTimes:
    stored: StoredCosplaySendStatusTimes
    display: display

MonthlyCard:
  MonthlyCard30:
    stored: StoredInt
    display: display
  MonthlyCard68:
    stored: StoredInt
    display: display

BattlePassStorage:
  BattlePassLevel:
    stored: StoredBattlePassLevel
    order: 5
    color: "#cbe45b"
    display: display
  MomentsGiveLike:
    type: checkbox
    value: 0
  ChannelSendIcon:
    type: checkbox
    value: 0

ItemStorage:
  Copper:
    stored: StoredInt
    order: 2
    color: "#6D412E"
    display: display
  TongBao:
    stored: StoredInt
    order: 3
    color: "#9CD4B8"
    display: display
  Power:
    stored: StoredPower
    order: 4
    color: "#e3a596"
    display: display

ClearJinGeTalisman:
  BuySuperCatBallWhenArriveRankNineEveryWeek:
    type: checkbox
    value: 1
  EndWhenTalismanIsClear:
    type: checkbox
    value: 1

JinGeStorage:
#  Talisman:
#    stored: StoredTalisman
#    display: disabled
  TalismanToClean:
    stored: StoredTalismanToClean
    display: disabled
  JinGeLevel:
    stored: StoredJinGeLevel
    display: disabled
  BuySuperCatBall:
    stored: StoredBuySuperCatBallWhenArriveRankNine
    display: disabled


DailyPassword:
  WechatInstallPath:
    type: textarea
    value: |-
      D:\WeChat\WeChat.exe
  OneWeekPasswordList:
    stored: StoredWeeklyPassword
    display: disabled
