# --------------------
# Define default values
# --------------------

# ==================== Alas ====================


# ==================== Daily ====================
#
Office:
  Scheduler:
    Enable: true
DailyShop:
  Scheduler:
    Enable: true
Cattery:
  Scheduler:
    Enable: true
Dispatch:
  Scheduler:
    Enable: true
Guild:
  Scheduler:
    Enable: true
Dungeon:
  Scheduler:
    Enable: true
#Dungeon:
#  Scheduler:
#    Enable: true
#DailyQuest:
#  Scheduler:
#    Enable: true
#BattlePass:
#  Scheduler:
#    Enable: true
#Assignment:
#  Scheduler:
#    Enable: true
#Freebies:
#  Scheduler:
#    Enable: true

# ==================== Weekly ====================

#Weekly:
#  DungeonSupport:
#    Use: do_not_use
