# --------------------
# Define default values
# --------------------

# ==================== Alas ====================


# ==================== Daily ====================
#
DailyQuest:
  Scheduler:
    Enable: true
MealPower:
  Scheduler:
    Enable: true
Guild:
  Scheduler:
    Enable: true
Shop:
  Scheduler:
    Enable: true

BattlePass:
  Scheduler:
    Enable: true

DataUpdate:
  Scheduler:
    Enable: true

Dungeon:
  Scheduler:
    Enable: true


# ==================== Weekly ====================

#Weekly:
#  DungeonSupport:
#    Use: do_not_use
