# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'list'
  page: 'setting'
  tasks:
    Alas:
      - Emulator
      - EmulatorInfo
      - Error
      - Optimization
    Restart:
      - Scheduler

# ==================== Daily ====================

Daily:
  menu: 'list'
  page: 'setting'
  tasks:
    Shop:
      - Scheduler
      - DailyShop
    Office:
      - Scheduler
      - Office
      - Visit
      - Meal
      - Affair
      - Jigsaw
      # - # todo:
    Cattery:
      - Scheduler
      - Cattery
      # - # todo:
      # - HideAndSeek
#    QilinNavi:
#      - Scheduler
#      # - # todo:
#    Yashe:
#      - Scheduler
#      # - # todo:
