# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'list'
  page: 'setting'
  tasks:
    Alas:
      - Emulator
      - EmulatorInfo
      - Error
      - Optimization
    Restart:
      - Scheduler

# ==================== Daily ====================

Daily:
  menu: 'list'
  page: 'setting'
  tasks:
    Shop:
      - Scheduler
      - Shop
      # - SupportReward # (Freebies?
    TaoYuan:
      - Scheduler
      - Taoyuanju
      # - # todo:
    Cattery:
      - Scheduler
      - Cattery
      # - # todo:
      # - HideAndSeek
#    QilinNavi:
#      - Scheduler
#      # - # todo:
#    Yashe:
#      - Scheduler
#      # - # todo:
