import datetime

# This file was automatically generated by module/config/config_updater.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    # Group `Scheduler`
    Scheduler_Enable = False  # True, False
    Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    Scheduler_Command = 'Alas'
    Scheduler_ServerUpdate = '06:00'

    # Group `Emulator`
    Emulator_Serial = 'auto'
    Emulator_GameClient = 'android'  # android, cloud_android
    Emulator_PackageName = 'auto'  # auto, CN-Official
    Emulator_GameLanguage = 'cn'  # auto, cn, en
    Emulator_ScreenshotMethod = 'auto'  # auto, ADB, ADB_nc, uiautomator2, aScreenCap, aScreenCap_nc, DroidCast, DroidCast_raw, scrcpy, nemu_ipc
    Emulator_ControlMethod = 'MaaTouch'  # minitouch, MaaTouch
    Emulator_AdbRestart = False

    # Group `EmulatorInfo`
    EmulatorInfo_Emulator = 'auto'  # auto, NoxPlayer, NoxPlayer64, BlueStacks4, BlueStacks5, BlueStacks4HyperV, BlueStacks5HyperV, LDPlayer3, LDPlayer4, LDPlayer9, MuMuPlayer, MuMuPlayerX, MuMuPlayer12, MEmuPlayer
    EmulatorInfo_name = None
    EmulatorInfo_path = None

    # Group `Error`
    Error_Restart = 'game'  # game, game_emulator
    Error_SaveError = True
    Error_ScreenshotLength = 1
    Error_OnePushConfig = 'provider: null'

    # Group `Optimization`
    Optimization_ScreenshotInterval = 0.3
    Optimization_CombatScreenshotInterval = 1.0
    Optimization_WhenTaskQueueEmpty = 'stay_there'  # stay_there, goto_main, close_game

    # Group `DailyStorage`
    DailyStorage_DailyLiveness = {}

    # Group `Office`
    Office_TransKaoGongTicket = 1
    Office_VisitOthersForClivia = 1

    # Group `Interact`
    Interact_CurrentCelebrity = 0
    Interact_CurrentAffectionLevel = 0

    # Group `Dungeon`
    Dungeon_Team = 1  # 1, 2, 3, 4, 5
    Dungeon_DailyBaoXuPlan = {}
    Dungeon_DailyJingYuanPlan = {}
    Dungeon_DailyGuShiFengYunPlan = {}
    Dungeon_DailyJinGePlan = {}

    # Group `MealPower`
    MealPower_UseTongBaoBuyExpiredPower = 1

    # Group `GuildActivity`
    GuildActivity_OpenActivityList = 0
    GuildActivity_ClearShaPanFlag = 0

    # Group `GuildMission`
    GuildMission_DailyGuildMission = {}
    GuildMission_WeeklyLiveness = 0

    # Group `MonthlyCard`
    MonthlyCard_MonthlyCard30 = {}
    MonthlyCard_MonthlyCard68 = {}

    # Group `ClearJinGeTalisman`
    ClearJinGeTalisman_BuySuperCatBallWhenArriveRankNineEveryWeek = 1
    ClearJinGeTalisman_EndWhenTalismanIsClear = 1

    # Group `JinGeStorage`
    JinGeStorage_TalismanToClean = {}
    JinGeStorage_JinGeLevel = {}
    JinGeStorage_BuySuperCatBall = {}

    # Group `DailyPassword`
    DailyPassword_OneWeekPasswordList = {}
